"""empty message

Revision ID: b882f83871b6
Revises: c304fe4b5e9c
Create Date: 2018-02-17 23:17:16.646286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b882f83871b6'
down_revision = 'c304fe4b5e9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('uuid', postgresql.UUID(as_uuid=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'uuid')
    # ### end Alembic commands ###
