"""empty message

Revision ID: c304fe4b5e9c
Revises: a2ddbc44154e
Create Date: 2018-02-14 21:48:57.093593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c304fe4b5e9c'
down_revision = 'a2ddbc44154e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('game', sa.Column('game_type_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'game', 'game_type', ['game_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_column('game', 'game_type_id')
    op.drop_table('game_type')
    # ### end Alembic commands ###
